// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// read_fasta
DataFrame read_fasta(std::string filename);
RcppExport SEXP _CamBioR_read_fasta(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_fasta(filename));
    return rcpp_result_gen;
END_RCPP
}
// read_fastq
DataFrame read_fastq(std::string filename);
RcppExport SEXP _CamBioR_read_fastq(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_fastq(filename));
    return rcpp_result_gen;
END_RCPP
}
// write_fasta
void write_fasta(DataFrame df, std::string path);
RcppExport SEXP _CamBioR_write_fasta(SEXP dfSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    write_fasta(df, path);
    return R_NilValue;
END_RCPP
}
// write_fastq
void write_fastq(DataFrame df, std::string path);
RcppExport SEXP _CamBioR_write_fastq(SEXP dfSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    write_fastq(df, path);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CamBioR_read_fasta", (DL_FUNC) &_CamBioR_read_fasta, 1},
    {"_CamBioR_read_fastq", (DL_FUNC) &_CamBioR_read_fastq, 1},
    {"_CamBioR_write_fasta", (DL_FUNC) &_CamBioR_write_fasta, 2},
    {"_CamBioR_write_fastq", (DL_FUNC) &_CamBioR_write_fastq, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CamBioR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
